on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'

defaults:
  run:
    shell: bash

name: Integration tests (skylake4x)
jobs:
  test-skylake4x:
    runs-on: [self-hosted, skylake4x]
    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init
          rustup show
      - name: Integration tests (qemu/kvm)
        run: |
          bash setup.sh
          cd kernel
          RUST_TEST_THREADS=1 cargo test --features smoke
  bench-skylake4x:
    needs: [test-skylake4x]
    runs-on: [self-hosted, skylake4x]
    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init
          rustup show
      - name: Run Benchmarks
        run: |
          bash setup.sh
          bash scripts/ci.bash
    env:
      CI_MACHINE_TYPE: "skylake4x"